name: Terraform CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  terraform:
    name: Terraform Workflow
    runs-on: self-hosted

    steps:

      # Step 1: Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Step 2: Validate Terraform configuration
      - name: Terraform Validate
        run: terraform validate

      # Step3 : Terraform Plan
      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan
        env:
          TF_LOG: DEBUG
          TF_VAR_pm_user: ${{ secrets.PM_USER }}
          TF_VAR_pm_password: ${{ secrets.PM_PASSWORD }}

      # Step 4: Apply (Optional - Triggered Manually)
      - name: Terraform Apply
        if: github.event_name == 'push'
        run: terraform apply -auto-approve tfplan
        env:
          TF_VAR_pm_user: ${{ secrets.PM_USER }}
          TF_VAR_pm_password: ${{ secrets.PM_PASSWORD }}
